### ISSUE TITLE
[Q] Authenticate and get friends locations from Snap Map.

### ISSUE THREAD

**Issue by soepketel-dev** [AlecAnthonyGarcia/snap-map-private-api#1]
Hello,

I was wondering if it is possible to gather the latlon (location) and last-seen of Snapchat friends from the Snapmap. Since there's an FRIENDS_MAP return I think you must be able to authenticate and obtain this data.

Please let me know.

**Comment by AlecAnthonyGarcia** [comment]
@totoberg123 There's currently no way to authenticate on the official Snap Map website, so this isn't possible. I'm sure that since they have included an empty "FRIENDS_MAP" and "FRIENDS_ALL" array, they will support authentication sometime in the future.

**Comment by jakenieto** [comment]
Is this still true? Are we unable to access this information from the API?
